/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import Game.Game;
import Graphics.GameWindow;
import Graphics.ResourceManager;
import Networking.Network;
import Player.*;

import javax.swing.*;

/**
 *
 * @author joemarch
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        player1AIOptions.setVisible(false);
        player1NetworkOptions.setVisible(false);
        player2AIOptions.setVisible(false);
        player2NetworkOptions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        this.setResizable(false);

        Player1Options = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        Player2Options = new javax.swing.ButtonGroup();
        Player2AIChoices = new javax.swing.ButtonGroup();
        player2NetworkChoices = new javax.swing.ButtonGroup();
        player1HumanOptions = new javax.swing.JPanel();
        player1Tag = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        player1Human = new javax.swing.JRadioButton();
        player1AI = new javax.swing.JRadioButton();
        player1Network = new javax.swing.JRadioButton();
        player1AIOptions = new javax.swing.JPanel();
        player1AIAggressive = new javax.swing.JRadioButton();
        player1AIConservative = new javax.swing.JRadioButton();
        player1NetworkOptions = new javax.swing.JPanel();
        player1NetworkClient = new javax.swing.JRadioButton();
        player1NetworkHost = new javax.swing.JRadioButton();
        player1HostName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        player2HumanOptions = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        player2Tag = new javax.swing.JTextField();
        player2Human = new javax.swing.JRadioButton();
        player2AI = new javax.swing.JRadioButton();
        player2Network = new javax.swing.JRadioButton();
        player2AIOptions = new javax.swing.JPanel();
        player2AIAggressive = new javax.swing.JRadioButton();
        player2AIConservative = new javax.swing.JRadioButton();
        player2NetworkOptions = new javax.swing.JPanel();
        player2NetworkClient = new javax.swing.JRadioButton();
        player2NetworkHost = new javax.swing.JRadioButton();
        player2HostName = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        player1HumanOptions.setBackground(new java.awt.Color(204, 204, 204));
        player1HumanOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        player1Tag.setText("Player 1");

        jLabel3.setText("Player Tag");

        javax.swing.GroupLayout player1HumanOptionsLayout = new javax.swing.GroupLayout(player1HumanOptions);
        player1HumanOptions.setLayout(player1HumanOptionsLayout);
        player1HumanOptionsLayout.setHorizontalGroup(
            player1HumanOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, player1HumanOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player1Tag)
                .addContainerGap())
            .addGroup(player1HumanOptionsLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        player1HumanOptionsLayout.setVerticalGroup(
            player1HumanOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1HumanOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1Tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Player1Options.add(player1Human);
        player1Human.setSelected(true);
        player1Human.setText("Human ");
        player1Human.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1HumanClicked(evt);
            }
        });

        Player1Options.add(player1AI);
        player1AI.setText("AI");
        player1AI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1AIClicked(evt);
            }
        });

        Player1Options.add(player1Network);
        player1Network.setText("Network");
        player1Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1NetworkClicked(evt);
            }
        });

        player1AIOptions.setBackground(new java.awt.Color(204, 204, 204));
        player1AIOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        buttonGroup1.add(player1AIAggressive);
        player1AIAggressive.setSelected(true);
        player1AIAggressive.setText("Aggressive");

        buttonGroup1.add(player1AIConservative);
        player1AIConservative.setText("Conservative");

        javax.swing.GroupLayout player1AIOptionsLayout = new javax.swing.GroupLayout(player1AIOptions);
        player1AIOptions.setLayout(player1AIOptionsLayout);
        player1AIOptionsLayout.setHorizontalGroup(
            player1AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1AIOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player1AIAggressive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(player1AIConservative)
                .addGap(22, 22, 22))
        );
        player1AIOptionsLayout.setVerticalGroup(
            player1AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1AIOptionsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(player1AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1AIAggressive)
                    .addComponent(player1AIConservative))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        player1NetworkOptions.setBackground(new java.awt.Color(204, 204, 204));
        player1NetworkOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        buttonGroup3.add(player1NetworkClient);
        player1NetworkClient.setSelected(true);
        player1NetworkClient.setText("Client");
        player1NetworkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NetworkClientClicked(evt);
            }
        });

        buttonGroup3.add(player1NetworkHost);
        player1NetworkHost.setText("Host");
        player1NetworkHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1NetworkHostClicked(evt);
            }
        });

        player1HostName.setText("localhost");

        javax.swing.GroupLayout player1NetworkOptionsLayout = new javax.swing.GroupLayout(player1NetworkOptions);
        player1NetworkOptions.setLayout(player1NetworkOptionsLayout);
        player1NetworkOptionsLayout.setHorizontalGroup(
            player1NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1NetworkOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(player1NetworkOptionsLayout.createSequentialGroup()
                        .addComponent(player1HostName)
                        .addContainerGap())
                    .addGroup(player1NetworkOptionsLayout.createSequentialGroup()
                        .addComponent(player1NetworkClient)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player1NetworkHost)
                        .addGap(71, 71, 71))))
        );
        player1NetworkOptionsLayout.setVerticalGroup(
            player1NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1NetworkOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player1NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1NetworkClient)
                    .addComponent(player1NetworkHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1HostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Player 2");

        jLabel2.setText("Player 1");

        player2HumanOptions.setBackground(new java.awt.Color(204, 204, 204));
        player2HumanOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        jLabel4.setText("Player Tag");

        player2Tag.setText("Player 2");

        javax.swing.GroupLayout player2HumanOptionsLayout = new javax.swing.GroupLayout(player2HumanOptions);
        player2HumanOptions.setLayout(player2HumanOptionsLayout);
        player2HumanOptionsLayout.setHorizontalGroup(
            player2HumanOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2HumanOptionsLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel4)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(player2HumanOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2Tag)
                .addContainerGap())
        );
        player2HumanOptionsLayout.setVerticalGroup(
            player2HumanOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2HumanOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(player2Tag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Player2Options.add(player2Human);
        player2Human.setSelected(true);
        player2Human.setText("Human");
        player2Human.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2HumanClicked(evt);
            }
        });

        Player2Options.add(player2AI);
        player2AI.setText("AI");
        player2AI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2AIClicked(evt);
            }
        });

        Player2Options.add(player2Network);
        player2Network.setText("Network");
        player2Network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NetworkClicked(evt);
            }
        });

        player2AIOptions.setBackground(new java.awt.Color(204, 204, 204));
        player2AIOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        Player2AIChoices.add(player2AIAggressive);
        player2AIAggressive.setSelected(true);
        player2AIAggressive.setText("Aggressive");

        Player2AIChoices.add(player2AIConservative);
        player2AIConservative.setText("Conservative");

        javax.swing.GroupLayout player2AIOptionsLayout = new javax.swing.GroupLayout(player2AIOptions);
        player2AIOptions.setLayout(player2AIOptionsLayout);
        player2AIOptionsLayout.setHorizontalGroup(
            player2AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2AIOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2AIAggressive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(player2AIConservative)
                .addGap(16, 16, 16))
        );
        player2AIOptionsLayout.setVerticalGroup(
            player2AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2AIOptionsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(player2AIOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2AIAggressive)
                    .addComponent(player2AIConservative))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        player2NetworkOptions.setBackground(new java.awt.Color(204, 204, 204));
        player2NetworkOptions.setPreferredSize(new java.awt.Dimension(203, 66));

        player2NetworkChoices.add(player2NetworkClient);
        player2NetworkClient.setSelected(true);
        player2NetworkClient.setText("Client");
        player2NetworkClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NetworkClientClicked(evt);
            }
        });

        player2NetworkChoices.add(player2NetworkHost);
        player2NetworkHost.setText("Host");
        player2NetworkHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player2NetworkHostClicked(evt);
            }
        });

        player2HostName.setText("localhost");

        javax.swing.GroupLayout player2NetworkOptionsLayout = new javax.swing.GroupLayout(player2NetworkOptions);
        player2NetworkOptions.setLayout(player2NetworkOptionsLayout);
        player2NetworkOptionsLayout.setHorizontalGroup(
            player2NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2NetworkOptionsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(player2NetworkClient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(player2NetworkHost)
                .addGap(68, 68, 68))
            .addGroup(player2NetworkOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2HostName)
                .addContainerGap())
        );
        player2NetworkOptionsLayout.setVerticalGroup(
            player2NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2NetworkOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(player2NetworkOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2NetworkClient)
                    .addComponent(player2NetworkHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player2HostName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(player1HumanOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(player1AIOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(player1NetworkOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(player1Human, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1AI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(player1Network, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(player2HumanOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(player2Human)
                .addGap(26, 26, 26)
                .addComponent(player2AI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(player2Network)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2AIOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(player2NetworkOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(okButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player1Human, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1AI, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1Network))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1HumanOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1AIOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(player1NetworkOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(player2Human)
                    .addComponent(player2AI)
                    .addComponent(player2Network))
                .addGap(5, 5, 5)
                .addComponent(player2HumanOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player2AIOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(player2NetworkOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(okButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1HumanClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1HumanClicked
        player1HumanOptions.setVisible(true);
        player1AIOptions.setVisible(false);
        player1NetworkOptions.setVisible(false);
    }//GEN-LAST:event_Player1HumanClicked

    private void Player1AIClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1AIClicked
        player1HumanOptions.setVisible(false);
        player1NetworkOptions.setVisible(false);
        player1AIOptions.setBounds(player1HumanOptions.getBounds());
        player1AIOptions.setVisible(true);
    }//GEN-LAST:event_Player1AIClicked

    private void Player1NetworkClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1NetworkClicked
        player1HumanOptions.setVisible(false);
        player1AIOptions.setVisible(false);
        player1NetworkOptions.setVisible(true);
        player1NetworkOptions.setBounds(player1HumanOptions.getBounds());
    }//GEN-LAST:event_Player1NetworkClicked

    private void player1NetworkClientClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NetworkClientClicked
        player1HostName.setVisible(true);
    }//GEN-LAST:event_player1NetworkClientClicked

    private void player1NetworkHostClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1NetworkHostClicked
        player1HostName.setVisible(false);
    }//GEN-LAST:event_player1NetworkHostClicked

    private void player2HumanClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2HumanClicked
        player2HumanOptions.setVisible(true);
        player2AIOptions.setVisible(false);
        player2NetworkOptions.setVisible(false);
    }//GEN-LAST:event_player2HumanClicked

    private void player2AIClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2AIClicked
        player2AIOptions.setBounds(player2HumanOptions.getBounds());
        player2HumanOptions.setVisible(false);
        player2AIOptions.setVisible(true);
        player2NetworkOptions.setVisible(false);
    }//GEN-LAST:event_player2AIClicked

    private void player2NetworkClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NetworkClicked
        player2Network.setBounds(player2HumanOptions.getBounds());
        player2HumanOptions.setVisible(false);
        player2AIOptions.setVisible(false);
        player2NetworkOptions.setVisible(true);
    }//GEN-LAST:event_player2NetworkClicked

    private void player2NetworkClientClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NetworkClientClicked
        player2HostName.setVisible(true);
    }//GEN-LAST:event_player2NetworkClientClicked

    private void player2NetworkHostClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player2NetworkHostClicked
        player2HostName.setVisible(false);
    }//GEN-LAST:event_player2NetworkHostClicked

    private void okButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonClicked
        Player player1 = null;
        Player player2 = null;

        if (player1Human.isSelected()) {
            player1 = new LocalHumanPlayer(player1Tag.getText(), true);
        } else if (player1AI.isSelected()) {
            if (player1AIAggressive.isSelected()) {
                player1 = new LocalAggressiveAIPlayer(true);
            } else if (player1AIConservative.isSelected()) {
                player1 = new LocalConservativeAIPlayer(true);
            }
        } else if (player1Network.isSelected()) {
            if (player1NetworkClient.isSelected()) {
                player1 = Network.makeCall(player1HostName.getText());
            } else if (player1NetworkHost.isSelected()) {
                player1 = Network.acceptCall();
            }

            if (player1 == null) {
                JOptionPane networkError = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(networkError, "Error with connecting to network, game failed");
                return;
            }
        }

        if (player2Human.isSelected()) {
            player2 = new LocalHumanPlayer(player2Tag.getText(), false);
        } else if (player2AI.isSelected()) {
            if (player2AIAggressive.isSelected()) {
                player2 = new LocalAggressiveAIPlayer(false);
            } else if (player2AIConservative.isSelected()) {
                player2 = new LocalConservativeAIPlayer(false);
            }
        } else if (player2Network.isSelected()) {
            if (player2NetworkClient.isSelected()) {
                player2 = Network.makeCall(player2HostName.getText());
            } else if (player2NetworkHost.isSelected()) {
                player2 = Network.acceptCall();
            }

            if (player2 == null) {
                JOptionPane networkError = new JOptionPane(JOptionPane.ERROR_MESSAGE);
                JOptionPane.showMessageDialog(networkError, "Error with connecting to network, game failed");
                return;
            }
        }

        Game game = new Game(player1, player2);
        new Thread(game).start();

    }//GEN-LAST:event_okButtonClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        ResourceManager.load();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Player1Options;
    private javax.swing.ButtonGroup Player2AIChoices;
    private javax.swing.ButtonGroup Player2Options;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton player1AI;
    private javax.swing.JRadioButton player1AIAggressive;
    private javax.swing.JRadioButton player1AIConservative;
    private javax.swing.JPanel player1AIOptions;
    private javax.swing.JTextField player1HostName;
    private javax.swing.JRadioButton player1Human;
    private javax.swing.JPanel player1HumanOptions;
    private javax.swing.JRadioButton player1Network;
    private javax.swing.JRadioButton player1NetworkClient;
    private javax.swing.JRadioButton player1NetworkHost;
    private javax.swing.JPanel player1NetworkOptions;
    private javax.swing.JTextField player1Tag;
    private javax.swing.JRadioButton player2AI;
    private javax.swing.JRadioButton player2AIAggressive;
    private javax.swing.JRadioButton player2AIConservative;
    private javax.swing.JPanel player2AIOptions;
    private javax.swing.JTextField player2HostName;
    private javax.swing.JRadioButton player2Human;
    private javax.swing.JPanel player2HumanOptions;
    private javax.swing.JRadioButton player2Network;
    private javax.swing.ButtonGroup player2NetworkChoices;
    private javax.swing.JRadioButton player2NetworkClient;
    private javax.swing.JRadioButton player2NetworkHost;
    private javax.swing.JPanel player2NetworkOptions;
    private javax.swing.JTextField player2Tag;
    // End of variables declaration//GEN-END:variables
}
